#!/usr/bin/env bash
#
# Summary: Utility library for developing bash scripts
#
# Usage: lasher <command> [<args>]
#
# Commands starting with an '_' are meant to be used from other scripts.
#
# Some useful lasher commands are:
#    help         Display help for a lasher command
#
# Some useful scripting commands are:
#    _help        Display help for any command
#
# See 'lasher help <command>' for information on a specific command.

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"")
  lasher-help
  ;;
* )
  command_path="$(command -v "lasher-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "lasher: no such command '$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
