#!/usr/bin/env bash
#
# Summary: Create a new empty command
#
# Usage: lasher new-command <prefix-command>
#
# Creates an empty command and an empty test.

command="$1"
command_file="libexec/${command}"
test_file="tests/${command}.bats"

test_template="#!/usr/bin/env bats

load test_helper"

if [ -e "$command_file" ]; then
  exit 1
fi

mkdir -p libexec
mkdir -p tests

echo "#!/usr/bin/env bash" > "$command_file"
chmod +x "$command_file"

echo "$test_template" > "$test_file"
