#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: lasher help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher-_help lasher
fi

lasher-_help "lasher-$command"
